"""
Sample client script for PNF Software' JEB2.

More samples are available on our website and within the scripts/ folder.

Refer to SCRIPTS.TXT for more information.
"""

from com.pnfsoftware.jeb.client.api import IScript


class JEB2SampleScript(IScript):
  def run(self, ctx):
    print('~~~\nThis line was generated by a JEB2 Python script\n~~~')
